FROM node:20 AS build-stage

WORKDIR /app

COPY . .

RUN npm install

RUN npx quasar build

FROM nginx:alpine AS production-stage

COPY --from=build-stage /app/dist/spa /usr/share/nginx/html

RUN echo "server { \
	listen 9000; \
	location / { \
		root /usr/share/nginx/html; \
		index index.html index.htm; \
		try_files \$uri \$uri/ /index.html; \
	} \
}" > /etc/nginx/conf.d/default.conf

EXPOSE 9000

CMD ["nginx", "-g", "daemon off;"]
