# backend/Dockerfile

# Usamos uma versão leve do Node.js
FROM node:20-alpine

# Define a pasta de trabalho dentro do container
WORKDIR /usr/src/app

# Copia apenas os arquivos de dependência primeiro (otimiza o cache do Docker)
COPY package*.json ./

# Instala as dependências
RUN npm install

# Copia o restante do código do backend
COPY . .

# Faz o build do código TypeScript para JavaScript
RUN npm run build

# Expõe a porta 3000 (a mesma que configuramos no Nest e no Compose)
EXPOSE 3000

# Comando para iniciar a API
CMD ["npm", "run", "start:prod"]